export const guestModal = {
    overlay: "fixed inset-0 z-[3000] flex items-center justify-center bg-coastal-primaryBright/64 p-[clamp(6px,1.6vw,20px)] backdrop-blur-[14px]",
    content: "relative flex max-h-[min(96dvh,760px)] w-[min(96vw,960px)] max-w-[960px] flex-col overflow-hidden rounded-[26px] border-2 border-[#caa65a] bg-[#fffdf8] text-coastal-ink shadow-[0_22px_58px_rgba(8,68,63,0.24),0_0_0_1px_rgba(138,93,31,0.42),inset_0_0_0_2px_rgba(255,255,255,0.96),inset_0_0_0_5px_rgba(202,166,90,0.13),inset_0_0_22px_rgba(202,166,90,0.2)]",
    back: "inline-flex min-h-[38px] items-center justify-center rounded-xl border border-[#caa65a]/50 bg-white px-3.5 text-[0.62rem] font-black uppercase tracking-[0.12em] text-coastal-primary shadow-[inset_0_0_0_2px_rgba(255,255,255,0.85)] transition hover:bg-coastal-secondarySoft",
    close: "absolute right-3 top-3 z-20 grid h-9 w-9 place-items-center rounded-full border border-[#caa65a]/55 bg-[#fffdf8]/92 text-coastal-ink opacity-100 shadow-[inset_0_0_0_2px_rgba(255,255,255,0.88),0_8px_18px_rgba(8,68,63,0.1)] transition hover:bg-coastal-secondarySoft",
    progress: "flex items-center justify-center gap-1 border-b border-[#caa65a]/40 bg-[#f7eedf]/62 px-12 py-2 shadow-[inset_0_1px_0_rgba(255,255,255,0.82)] max-[560px]:px-3",
    progressStep: "inline-flex min-h-7 min-w-[92px] items-center justify-center rounded-xl border border-[#d8c9b3]/80 bg-[#fffdf8]/78 px-3 text-center text-[0.55rem] font-black uppercase tracking-[0.12em] text-coastal-muted shadow-[inset_0_1px_0_rgba(255,255,255,0.72)] transition max-[560px]:min-w-0 max-[560px]:flex-1 max-[560px]:px-2",
    progressStepActive: "border-coastal-primary/35 text-coastal-primary",
    progressStepCurrent: "border-[#0a6b5f] bg-[linear-gradient(180deg,#0d766a_0%,#075f55_100%)] text-[#fffdf8] shadow-[0_8px_18px_rgba(10,107,95,0.18),inset_0_1px_0_rgba(255,255,255,0.22)]",
    progressDiv: "hidden",
    step: "min-h-0 overflow-y-auto px-[clamp(14px,2.2vw,24px)] pb-[clamp(10px,2vw,20px)] pt-[clamp(12px,2vw,20px)] [scrollbar-color:var(--accent-green)_var(--bg-secondary)] [scrollbar-width:thin]",
    stepFlush: "overflow-y-auto p-0 [scrollbar-color:var(--accent-green)_var(--bg-secondary)] [scrollbar-width:thin]",
    label: "mb-1.5 block text-[0.62rem] font-black uppercase tracking-[0.15em] text-coastal-primary",
    roomTitle: "m-0 font-display text-[clamp(1.45rem,2.5vw,2.15rem)] font-bold leading-none text-coastal-ink",
    sectionTitle: "mb-3 mt-0 font-display text-[clamp(1.35rem,2.4vw,2rem)] font-bold leading-none text-coastal-ink",
    bookingRef: "mb-1 mt-0 font-display text-[clamp(1.35rem,2.4vw,2rem)] font-bold leading-none text-coastal-ink",
    desc: "mb-3 text-[0.76rem] leading-[1.45] text-coastal-muted",
    gridTwo: "grid grid-cols-1 gap-3 min-[560px]:grid-cols-2",
    fullSpan: "min-[560px]:col-span-2",
    stack: "flex flex-col gap-3",
    labelSmall: "mb-1.5 block text-[0.62rem] font-black uppercase tracking-[0.15em] text-coastal-primary",
    dateWrap: "relative rounded-xl border border-[#caa65a]/45 bg-white shadow-[inset_0_0_0_2px_rgba(255,255,255,0.82)]",
    dateInput: "min-h-[38px] w-full rounded-xl border-0 bg-transparent px-3 py-0 text-[0.82rem] font-extrabold text-coastal-ink outline-none [color-scheme:light]",
    calBtn: "hidden",
    textInput: "min-h-[38px] w-full rounded-xl border border-[#caa65a]/45 bg-white px-3 py-0 text-[0.84rem] font-extrabold text-coastal-ink outline-none [color-scheme:light] placeholder:text-coastal-muted/55 focus:border-coastal-primary",
    hint: "mt-1 text-[0.66rem] leading-4 text-coastal-muted",
    hintBold: "rounded-full bg-coastal-secondarySoft px-2 py-1 text-[0.68rem] font-black text-coastal-tertiary",
    error: "mt-3 rounded-[14px] border border-coastal-coral/20 bg-coastal-coral/10 px-3 py-2.5 text-[0.74rem] font-extrabold text-coastal-coral",
    actionRight: "mt-3 flex justify-end",
    actionBetween: "mt-3 grid grid-cols-[auto_1fr] items-center gap-2.5",
    paymentActionBar: "sticky bottom-0 z-10 -mx-[clamp(14px,2.2vw,24px)] mt-3 grid grid-cols-[auto_1fr] items-center gap-2.5 border-t border-[#caa65a]/35 bg-[#fffdf8]/95 px-3.5 py-2.5 shadow-[0_-12px_24px_rgba(8,68,63,0.1)] backdrop-blur-xl",
    primaryBtn: "inline-flex min-h-[42px] items-center justify-center rounded-xl border-2 border-[#caa65a]/80 bg-[linear-gradient(135deg,#0c755f,#034638)] px-5 py-2.5 text-[0.64rem] font-black uppercase tracking-[0.13em] text-white shadow-[0_10px_20px_rgba(3,70,56,0.28),inset_0_1px_0_rgba(255,255,255,0.16)] transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60 max-[640px]:w-full",
    ghostBtn: "inline-flex min-h-[42px] items-center justify-center rounded-xl border border-[#caa65a]/50 bg-white px-4 text-[0.68rem] font-black uppercase tracking-[0.13em] text-coastal-muted transition hover:text-coastal-primary",
    commitBox: "mt-3 rounded-[18px] border border-coastal-outline/50 bg-gradient-to-b from-coastal-surface to-coastal-surfaceLow p-3 shadow-breezeSm",
    commitButtons: "flex gap-2.5 max-[520px]:flex-col",
    choiceBtn: "min-h-[36px] flex-1 rounded-full border border-[#caa65a]/55 bg-white px-4 text-[0.62rem] font-black uppercase tracking-[0.11em] text-coastal-ink transition",
    choiceBtnSelected: "!border-[#caa65a] !bg-[linear-gradient(135deg,#0c755f,#034638)] !text-white shadow-[0_8px_16px_rgba(3,70,56,0.18)]",
    priceRows: "mt-3 flex flex-col gap-1.5 border-t border-coastal-outline pt-3",
    priceRow: "flex justify-between gap-4 text-[0.73rem]",
    priceMuted: "text-coastal-muted",
    priceBold: "font-black text-coastal-primaryBright",
    priceRed: "font-black text-coastal-coral",
    warning: "mb-4 rounded-2xl border border-coastal-secondary/30 bg-coastal-secondary/10 px-4 py-3.5 text-coastal-tertiary",
    methodRow: "mb-3 flex gap-2",
    qrCard: "grid cursor-zoom-in grid-cols-[auto_1fr] gap-3 rounded-[18px] border border-coastal-outline bg-gradient-to-br from-coastal-surface to-coastal-surfaceLow p-3 shadow-breezeSm",
    qrThumbWrap: "relative overflow-hidden rounded-2xl border border-coastal-outline",
    qrThumb: "block h-28 w-28 object-cover max-[420px]:h-24 max-[420px]:w-24",
    qrHint: "absolute inset-x-0 bottom-0 bg-coastal-primaryBright/80 px-2 py-1 text-center text-[0.54rem] font-black uppercase tracking-[0.1em] text-white",
    qrBank: "text-[0.68rem] font-black uppercase tracking-[0.16em] text-coastal-primary",
    qrName: "mt-1.5 font-display text-[1.12rem] font-bold leading-tight text-coastal-ink",
    qrNum: "mt-0.5 text-[0.9rem] font-black text-coastal-ink",
    qrSub: "mt-1.5 text-[0.7rem] font-bold text-coastal-muted",
    uploadZone: "mt-3 rounded-[16px] border border-dashed border-coastal-primary/40 bg-coastal-secondarySoft/50 p-4 text-center transition",
    uploadZoneFile: "border-coastal-primary bg-coastal-secondarySoft",
    uploadLabel: "text-[0.7rem] font-black uppercase tracking-[0.14em] text-coastal-primaryBright",
    uploadDone: "m-0 text-[0.76rem] font-black uppercase tracking-[0.12em] text-coastal-primaryBright",
    savedRef: "mt-3 rounded-[14px] border border-coastal-outline bg-coastal-surface p-3",
    submitBtn: "inline-flex min-h-[42px] w-full items-center justify-center rounded-xl border-2 border-[#caa65a]/80 bg-[linear-gradient(135deg,#0c755f,#034638)] px-5 py-2.5 text-[0.64rem] font-black uppercase tracking-[0.13em] text-white shadow-[0_10px_20px_rgba(3,70,56,0.28),inset_0_1px_0_rgba(255,255,255,0.16)] transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60",
    outlineBtn: "inline-flex min-h-[46px] items-center justify-center rounded-full border border-coastal-outline bg-coastal-surface px-5 py-3 text-[0.7rem] font-black uppercase tracking-[0.13em] text-coastal-ink",
    receiptActions: "flex gap-2.5 pt-4",
    builderShell: "grid grid-cols-[minmax(0,1fr)_minmax(260px,0.34fr)] gap-3 max-[900px]:grid-cols-1",
    builderGrid: "grid grid-cols-2 gap-2.5",
    modeToggle: "mt-2.5 grid grid-cols-2 gap-2 rounded-full border border-[#caa65a]/45 bg-white p-1 max-[520px]:rounded-[18px]",
    selectedPanel: "mt-2.5 rounded-2xl border border-[#caa65a]/32 bg-white/72 p-2.5 shadow-[inset_0_0_0_1px_rgba(255,255,255,0.7)] max-[640px]:hidden",
    builderHead: "mb-2 flex items-center justify-between gap-3",
    builderKicker: "m-0 text-[0.66rem] font-black uppercase tracking-[0.15em] text-coastal-primary",
    builderCount: "shrink-0 rounded-full bg-coastal-primary/10 px-2.5 py-1 text-[0.62rem] font-black uppercase tracking-[0.08em] text-coastal-primaryBright",
    selectedList: "flex flex-col gap-1.5",
    selectedChip: "grid w-full grid-cols-[54px_1fr] gap-2.5 rounded-[14px] border border-[#caa65a]/34 bg-white p-2 text-left shadow-[0_8px_16px_rgba(8,68,63,0.06)] transition hover:border-coastal-primary/42",
    selectedChipImg: "h-[54px] w-[54px] rounded-[10px] object-cover",
    selectedChipTop: "flex items-start justify-between gap-3",
    selectedChipTitle: "text-[0.9rem] font-black text-coastal-ink",
    selectedChipMeta: "mt-1 text-[0.72rem] font-bold text-coastal-muted",
    selectedChipRemove: "rounded-full bg-coastal-coral/10 px-2.5 py-1 text-[0.58rem] font-black uppercase tracking-[0.1em] text-coastal-coral",
    unitTagRow: "mt-1.5 flex flex-wrap gap-1.5",
    unitTag: "rounded-full bg-coastal-secondarySoft px-2 py-1 text-[0.58rem] font-black uppercase tracking-[0.08em] text-coastal-tertiary",
    unitBrowserPanel: "mt-2.5 rounded-2xl border border-[#caa65a]/32 bg-white/62 p-3",
    unitBrowserNote: "mb-2 text-[0.68rem] leading-4 text-coastal-muted",
    unitUnavailableAlert: "mb-3 rounded-[14px] border border-coastal-coral/20 bg-coastal-coral/10 px-3 py-2.5 text-[0.76rem] font-bold text-coastal-coral",
    unitBrowser: "max-h-[228px] overflow-y-auto pr-1 [scrollbar-color:var(--accent-green)_var(--bg-secondary)] [scrollbar-width:thin] max-[640px]:max-h-[172px]",
    unitGroup: "mb-2.5 last:mb-0",
    unitGrid: "grid grid-cols-1 gap-2",
    unitCard: "grid w-full grid-cols-[64px_1fr] gap-3 rounded-[14px] border border-[#caa65a]/36 bg-white p-2 text-left shadow-[0_8px_16px_rgba(8,68,63,0.06)] transition hover:border-coastal-primary/48 disabled:cursor-not-allowed max-[520px]:grid-cols-[58px_1fr]",
    unitCardSelected: "border-coastal-primary bg-coastal-secondarySoft",
    unitCardUnavailable: "opacity-55 grayscale",
    unitCardThumbWrap: "overflow-hidden rounded-[12px]",
    unitCardThumb: "h-16 w-16 object-cover max-[520px]:h-[58px] max-[520px]:w-[58px]",
    unitCardMain: "min-w-0",
    unitCardTop: "flex items-start justify-between gap-3",
    unitCardTitle: "text-[0.9rem] font-black text-coastal-ink",
    unitCardSub: "mt-0.5 text-[0.7rem] font-bold text-coastal-muted",
    unitCardAction: "shrink-0 rounded-full bg-coastal-primary/10 px-2.5 py-1 text-[0.58rem] font-black uppercase tracking-[0.1em] text-coastal-primaryBright",
    unitCardBody: "mt-2",
    unitCompactMeta: "flex flex-wrap items-center gap-1.5",
    unitBadge: "rounded-full bg-coastal-secondarySoft px-2 py-1 text-[0.58rem] font-black uppercase tracking-[0.08em] text-coastal-tertiary",
    unitUnavailableText: "text-[0.68rem] font-bold text-coastal-coral",
    unitPrice: "text-[0.68rem] font-black text-coastal-primaryBright",
    summaryStick: "sticky top-0 max-[900px]:hidden",
    summaryCard: "rounded-2xl border border-[#caa65a]/42 bg-white/76 p-3 shadow-[inset_0_0_0_1px_rgba(255,255,255,0.72),0_10px_20px_rgba(8,68,63,0.08)]",
    summaryLead: "mb-2.5 text-[0.76rem] leading-5 text-coastal-muted",
    summaryWarning: "mb-3 rounded-[14px] border border-coastal-secondary/30 bg-coastal-secondary/10 px-3 py-2.5 text-[0.76rem] font-bold leading-5 text-coastal-tertiary",
    summaryPill: "rounded-xl border border-[#caa65a]/34 bg-white p-2.5",
    desktopAction: "mt-3 flex justify-end max-[640px]:hidden",
    mobileActionBar: "sticky bottom-0 z-10 -mx-[clamp(14px,2.2vw,24px)] mt-2.5 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2.5 border-t border-[#caa65a]/35 bg-[#fffdf8]/95 px-3.5 py-2.5 shadow-[0_-12px_24px_rgba(8,68,63,0.1)] backdrop-blur-xl min-[641px]:hidden",
    mobileActionText: "min-w-0 text-[0.7rem] font-bold leading-4 text-coastal-muted",
    mobileActionStrong: "block truncate text-[0.78rem] font-black text-coastal-primaryBright",
    noteBox: "mb-4 rounded-[14px] border border-coastal-outline bg-coastal-surfaceLow px-3.5 py-3 text-coastal-ink",
    guardOverlay: "absolute inset-0 z-30 grid place-items-center bg-coastal-primaryBright/62 p-5 backdrop-blur-sm",
    guardBox: "w-[min(92vw,360px)] rounded-[22px] border border-coastal-outline bg-coastal-surface p-5 shadow-breezeResort",
    guardActions: "flex gap-2.5",
    guardStay: "min-h-10 flex-1 rounded-full border border-coastal-primary/80 bg-coastal-primary px-4 text-[0.66rem] font-black uppercase tracking-[0.1em] text-white",
    guardLeave: "min-h-10 flex-1 rounded-full border border-coastal-coral/20 bg-coastal-coral/10 px-4 text-[0.66rem] font-black uppercase tracking-[0.1em] text-coastal-coral",
    lightbox: "fixed inset-0 z-[9999] flex cursor-zoom-out flex-col items-center justify-center bg-[rgba(10,14,12,0.93)] p-5 backdrop-blur-md",
    lightboxClose: "fixed right-5 top-5 z-[10000] grid h-10 w-10 place-items-center rounded-full border border-white/20 bg-white/10 text-white transition hover:bg-white/20",
    lightboxImg: "max-h-[75vh] max-w-[min(88vw,420px)] cursor-default rounded-xl object-contain shadow-[0_30px_80px_rgba(0,0,0,0.6)]",
    lightboxHint: "mt-5 text-[0.65rem] tracking-[1px] text-white/30",
};

export const progressStepClass = (active, current) => [
    guestModal.progressStep,
    active ? guestModal.progressStepActive : '',
    current ? guestModal.progressStepCurrent : '',
].filter(Boolean).join(' ');

export const choiceClass = (selected) => [
    guestModal.choiceBtn,
    selected ? guestModal.choiceBtnSelected : '',
].filter(Boolean).join(' ');

export const uploadZoneClass = (hasFile) => [
    guestModal.uploadZone,
    hasFile ? guestModal.uploadZoneFile : '',
].filter(Boolean).join(' ');

export const unitCardClass = (selected, unavailable) => [
    guestModal.unitCard,
    selected ? guestModal.unitCardSelected : '',
    unavailable ? guestModal.unitCardUnavailable : '',
].filter(Boolean).join(' ');
