/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        breeze: {
          canvas: 'var(--amalfi-canvas)',
          surface: 'var(--amalfi-surface)',
          surfaceSoft: 'var(--amalfi-surface-soft)',
          ink: 'var(--amalfi-ink)',
          muted: 'var(--amalfi-muted)',
          line: 'var(--amalfi-line)',
          emerald: 'var(--amalfi-emerald)',
          emeraldDeep: 'var(--amalfi-emerald-deep)',
          emeraldSoft: 'var(--amalfi-emerald-soft)',
          gold: 'var(--amalfi-gold)',
          coral: 'var(--amalfi-coral)',
          lagoon: 'var(--amalfi-lagoon)',
          sand: 'var(--amalfi-sand)',
          night: 'var(--amalfi-night)',
        },
        resort: {
          bg: '#fef9f0',
          surface: '#fffdf8',
          ivory: '#fffdf8',
          emerald: '#0a6b5f',
          emeraldDark: '#005147',
          lagoon: '#85d5c6',
          gold: '#c6923f',
          sand: '#f2ede4',
          line: '#bec9c5',
          ink: '#1d1c16',
          muted: '#3e4946',
          coral: '#ba1a1a',
        },
        coastal: {
          background: '#fef9f0',
          surface: '#fffdf8',
          surfaceLow: '#f8f3ea',
          surfaceContainer: '#f2ede4',
          surfaceHigh: '#e7e2d9',
          primary: '#0a6b5f',
          primaryBright: '#005147',
          secondary: '#c6923f',
          secondarySoft: '#a1f2e2',
          tertiary: '#474744',
          gold: '#c6923f',
          ink: '#1d1c16',
          muted: '#3e4946',
          outline: '#bec9c5',
        },
      },
      boxShadow: {
        breezeSm: 'var(--amalfi-shadow-sm)',
        breezeMd: 'var(--amalfi-shadow-md)',
        breezeResort: 'var(--amalfi-shadow-resort)',
        guestCard: '0 18px 44px rgba(19, 33, 31, 0.075)',
      },
      borderRadius: {
        breezeMd: 'var(--amalfi-radius-md)',
        breezeLg: 'var(--amalfi-radius-lg)',
        breezeXl: 'var(--amalfi-radius-xl)',
      },
      fontFamily: {
        sans: ['var(--font-body)'],
        display: ['var(--font-heading)'],
        mono: ['var(--font-mono)'],
      },
      backgroundImage: {
        guestCanvas: 'linear-gradient(180deg, rgba(255,253,248,0.92), rgba(244,239,230,0.98))',
        tropicalGlass: 'linear-gradient(135deg, rgba(255,253,248,0.9), rgba(232,245,240,0.52))',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
